### ISSUE TITLE
Crash while using shaderpacks

### ISSUE THREAD

**Issue by Werneq** [Tralty/Adventure-of-Tech-V#1]
Pack comes with ComplementaryUnbound_r5.2.2 enabled, which crashes at world login. If I disable goes fine. Either Reimagined or Unbound crashes, even if I enable it after world login.

Steps:
**1-** Download fresh pack from curseforge (I'm using Prism launcher)
**2-** Launch the game
**3-** Click in Single Player and create a new world
**4-** Game will crash after creation, during login process. **<--------- CRASH**

[crash-2024-12-02_19.46.23-client.txt](https://github.com/user-attachments/files/17984801/crash-2024-12-02_19.46.23-client.txt)

**Comment by Werneq** [comment]
Update to the issue, ComplementaryUnbound_r5.3 will not crash. So its very easy to fix, just ship the pack with the latest version.

I downloaded the last version here: https://modrinth.com/shader/complementary-unbound/version/r5.3

**Comment by Tralty** [comment]
Thanks for letting me know! I'll get to updating the shaders as soon as I can!
